### ISSUE TITLE
Problem with mockster

### ISSUE THREAD

**Issue by rtens** [rtens/dox#23]
http://dox.rtens.org/projects/rtens-mockster

**Comment by rtens** [comment]
```
Exception: Project folder already exists [/var/www/virtual/rtens/dox.rtens.org/user/projects/rtens-mockster]
#0 /var/www/virtual/rtens/dox.rtens.org/src/rtens/dox/web/root/projects/xxProjectResource.php(78): rtens\dox\VcsService->checkout(Object(rtens\dox\Project))
#1 /var/www/virtual/rtens/dox.rtens.org/src/rtens/dox/web/root/projects/xxProjectResource.php(63): rtens\dox\web\root\projects\xxProjectResource->assembleNavigation(Object(rtens\dox\Project), Object(Closure))
#2 /var/www/virtual/rtens/dox.rtens.org/src/rtens/dox/web/root/projects/xxProjectResource.php(37): rtens\dox\web\root\projects\xxProjectResource->assembleModel(Object(rtens\dox\Project))
#3 [internal function]: rtens\dox\web\root\projects\xxProjectResource->doGet('rtens-mockster')
#4 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/resource/DynamicResource.php(71): ReflectionMethod->invokeArgs(Object(rtens\dox\web\root\projects\xxProjectResource), Array)
#5 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/resource/DynamicResource.php(34): watoki\curir\resource\DynamicResource->invokeMethod('get', Object(watoki\collections\Map))
#6 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/resource/Container.php(15): watoki\curir\resource\DynamicResource->respond(Object(watoki\curir\http\Request))
#7 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/resource/Container.php(25): watoki\curir\resource\Container->respond(Object(watoki\curir\http\Request))
#8 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/resource/Container.php(25): watoki\curir\resource\Container->respond(Object(watoki\curir\http\Request))
#9 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/WebApplication.php(86): watoki\curir\resource\Container->respond(Object(watoki\curir\http\Request))
#10 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/WebApplication.php(63): watoki\curir\WebApplication->getResponse(Object(watoki\curir\http\Request))
#11 /var/www/virtual/rtens/dox.rtens.org/vendor/watoki/curir/src/watoki/curir/WebApplication.php(46): watoki\curir\WebApplication->run()
#12 /var/www/virtual/rtens/dox.rtens.org/index.php(16): watoki\curir\WebApplication::quickStart('rtens\\dox\\web\\R...', Object(watoki\factory\Factory))
#13 {main}
